swagger: "2.0"
info:
  description: This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
consumes:
  - application/json
produces:
  - application/json
  
host: petstore.swagger.io
basePath: /api
tags:
- name: processors
  description: Everything about Processors
- name: motherboards
  description: Everything about Motherboards
- name: memorie sticks
  description: Everything about Ram Memory
- name: graphics cards
  description: Everything about Graphics Cards
- name: storage
  description: Everything about Storage disks
- name: power suplies
  description: Everything about Power Suplies
- name: fans
  description: Everything about Fans
- name: cases
  description: Everything about Computer Cases
- name: coolers
  description: Everything about Cooling
- name: parts
  description: search for parts
schemes:
- https
- http
paths:
  /power_supplies/:
    get:
      tags:
      - power suplies
      summary: Get power supplies by potency
      operationId: get_power_supplies
      produces:
      - application/xml
      - application/json
      parameters:
      - name: min_potency
        in: query
        description: The minimum potency of the power supply.
        type: integer
        format: int32
        required: false
      - name: max_potency
        in: query
        description: The maximum potency of the power supply.
        type: integer
        format: int32
        required: false
      - name: manufacturer
        in: query
        description: The manufacturer of the power supply
        type: string
        required: false
      - name: modular
        in: query
        description: The modularity of the power supply
        type: string
        enum:
        - Full modular
        - Semi modular
        - Not modular
        required: false
      - name: form_factor
        in: query
        description: The form factor of the power supply
        type: string
        enum:
        - ATX
        - ATX / BTX
        - ATX12V
        - ATX12V / EPS12V
        - Flex ATX
        - Micro ATX
        - Mini ATX
        - Mini ITX
        - SFX12V
        - TFX12V
        required: false
      - name: color
        in: query
        description: The color of the power supply
        type: string
        required: false
      - name: fan
        in: query
        description: Wether the power supply has a fan or Not
        type: boolean
        required: false
      - name: connectors
        in: query
        description: The types of connectors of the power supply
        type: string
        required: false
      - name: effeciency
        in: query
        type: string
        enum:
        - 80+
        - 80+ Bronze
        - 80+ Silver
        - 80+ Gold
        - 80+ Platinum
        - 80+ Titanium
        required: false
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Part"
        400:
          description: Invalid Parameters
  /fans:
    get:
      tags:
        - fans
      summary: Get a list of fans
      operationId: get_fans
      produces:
      - application/json
      - application/xml
      parameters: 
        - name: manufacturer
          in: query
          type: string
          required: false
        - name: size
          in: query
          type: string
          enum:
          - 40 mm
          - 70 mm
          - 80 mm
          - 92 mm
          - 95 mm
          - 120 mm
          - 180 mm
          - 193 mm
          - 200 mm
          - 220 mm
          - 230 mm
          required: false
        - name: color
          in: query
          type: string
          required: false
        - name: quantidade
          in: query
          type: integer
          required: false
        - name: PWM
          in: query
          type: boolean
          required: false
        - name: led
          in: query
          type: string
          enum:
          - RGB
          - Addressable RGB
          - Multicolor
          - Single color
          - Blue
          - Green
          - Orange
          - Pink
          - Purple
          - Red
          - UV
          - UV Blue
          - UV Green
          - UV Red
          - White
          - Yellow
          required: false
        - name: connector
          in: query
          type: string
          enum:
          - 3-pin
          - 4-pin PWM
          - 4-pin 12V RGB
          - Proprietary RGB
          - 3-pin 5V Addressable RGB
          - Proprietary
          - Proprietary PWM
          required: false
        - name: controler
          in: query
          type: string
          enum:
          - Manual
          - USB
          - 12V RGB
          - 5V Addressable RGB
          required: false
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Part"
        400: 
          description: Invalid Parameters 
  /cases:
    get:
      tags:
      - cases
      summary: Get a list of cases
      operationId: get_cases
      produces:
      - application/json
      - application/xml
      parameters: 
        - name: manufacturer
          in: query
          type: string
          required: false
        - name: case_type
          in: query
          type: string
          enum:
            - Full Tower
            - Mid Tower
            - Mini Tower
            - Slim Line
            - Small Form Factor
          required: false
        - name: motherboard_form_factor
          in: query
          type: string
          enum:
            - Full ATX
            - Mini ATX
            - Micro ATX
            - Flex ATX
            - Mini ITX
            - Em ITX
            - Nano ITX
            - Pico ITX
            - Mobile ITX
            - DTX
            - Mini DTX
            - SSI
            - SSI EEB
            - E-ATX
            - Extended ATX
            - SSI MEB
            - BTX
            - NLX
          required: false
        - name: color
          in: query
          type: string
          required: false
        - name: side_panel_window
          in: query
          type: string
          enum:
          - Acrylic
          - Mesh
          - Tinted Acrylic
          - Tempered Glass
          - Tinted Tempered Glass
          required: false
        - name: shroud
          in: query
          type: boolean
          required: false
        - name: front_panel
          in: query
          type: string
          enum:
          - USB 3.2 Gen 2x2 Type-C
          - USB 3.2 Gen 2 Type-C
          - USB 3.2 Gen 1 Type-C
          - USB 3.2 Gen 1 Type-A
          - USB 2.0 Type-A
          required: false
        - name: min_graphics_card_length
          in: query
          type: integer
          required: false
        - name: max_graphics_card_length
          in: query
          type: integer
          required: false
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Part"
        400:
          description: Invalid Parameters
  /coolers:
    get:
      tags:
        - coolers
      summary: get a list of coolers
      operationId: get_coolers
      produces:
      - application/json
      - application/xml
      parameters:
        - name: manufacturer
          in: query
          type: string
          required: false
        - name: color
          in: query
          type: string
          required: false
        - name: socket_compatability
          in: query
          type: string
          required: false
        - name: max_heatsink_height
          description: The max height the heatsink can have in milimetres
          in: query
          type: integer
          format: int32
          required: false
        - name: min_heatsink_height
          description: The min height the heatsink can have in milimetres
          in: query
          type: integer
          format: int32
          required: false
        - name: fan
          in: query
          type: boolean
          required: false
        - name: radiator_size
          in: query
          type: string
          enum:
          - 120 mm
          - 140 mm
          - 240 mm
          - 280 mm
          - 360 mm
          - 420 mm
          required: false
        # water coolers?
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Part"
        400:
          description: Invalid Parameters
  /parts/:
    get:
      tags: 
        - parts
      summary: search for parts
      operationId: search_part
      produces:
      - application/json
      - application/xml
      parameters:
        - name: sku
          in: query
          type: string
          required: false
        - name: part name
          in: query
          type: string
          required: false
        - name: manufacturer
          in: query
          type: string
          required: false
        - name: color
          in: query
          type: string
          required: false
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Part"
        400:
          description: Invalid Parameters
definitions:
  Part:
    type: object
    properties:
      sku:
        type: string
      price:
        type: number
        format: double
  CaseType: 
    type: string
    enum:
      - Full Tower
      - Mid Tower
      - Mini Tower
      - Slim Line
      - Small Form Factor
  MotherboardFormFactor:
    type: string
    enum:
      - AT
      - ATX
      - EATX
      - Flex ATX
      - HPTX
      - Micro ATX
      - Mini ITX
      - Thin Mini ITX
      - Mini DTX
      - SSI CEB
      - SSI EEB
      - XL ATX