openapi: 3.0.1
info:
  title: Scrapping Service
  description: This sevice provides up to date information regarding computer component prices in major technology shops in Portugal
  version: 1.0.1
tags:
- name: Configuration 
  description: Create, update and get the configurations

paths:
  /configuration/{configurationId}:
    get:
      tags:
      - Configuration
      summary: get configuration information by id
      operationId: configuration_handler.get_configuration_by_id
      parameters:
      - name: configurationId
        in: path
        description: the id of the configuration
        required: True
        schema:
          type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
            application/xml:
              schema:
                $ref: '#/components/schemas/Configuration'   
    put:
      tags:
      - Configuration 
      summary: update configuration
      operationId: configuration_handler.update_configuration
      parameters:
      - name: configurationId
        in: path
        description: the id of the configuration
        required: True
        schema:
          type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
  /configuration/{username}:
    get:
      tags:
      - Configuration
      summary: get configuration information by user id
      operationId: configuration_handler.get_configuration_by_user_id
      parameters:
      - name: username
        in: path
        description: the id of the user
        required: True
        schema:
          type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
            application/xml:
              schema:
                $ref: '#/components/schemas/Configuration'
    post:
      tags:
      - Configuration 
      summary: create configuration 
      operationId: configuration_handler.create_configuration
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: configuration
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
components:
  schemas:
    Configuration:
      type: object
      properties:
        user:
          type: string
        uuid:
          type: string
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
    Part:
      type: object
      properties:
        part_type:
          type: string
        part_sku: 
          type: string
