openapi: 3.0.1
info:
  title: Clickfield Data Service
  description: This service profides information on the prices of computer parts from the chiptec online store.
  version: 1.0.2
tags:
- name: Part Prices
  description: Part prices from clickfield
paths:
  /parts/:
    get:
      tags:
      - Part Prices
      summary: Get The price for a list of skus
      operationId: click_field_handler.get_parts
      parameters:
      - name: sku_list
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: success
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartPrice'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartPrice'
    post:
      tags:
      - Part Prices
      summary: update the data of the service
      operationId: click_field_handler.update_prices
      parameters: []
      requestBody:
        description: product descriptions to add
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PartPrice'
          application/xml:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PartPrice'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
  /parts/{sku}:
    get:
      tags:
      - Part Prices
      summary: Get The price for a sku
      operationId: click_field_handler.get_part
      parameters:
      - name: sku
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartPrice'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartPrice'
components:
  schemas:
    PartPrice:
      type: object
      properties:
        sku:
          type: string
        timestamp:
          type: number
        ean:
          type: string
        price:
          type: number
          format: double